apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Release.Name }}-canary
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-cafeweb
  service:
    port: 80
    targetPort: 80
    gateways:
      - {{ .Release.Name }}-gateway
    hosts:
      - "*"
  analysis:
    interval: 1m
    threshold: 3
    maxWeight: 60
    stepWeight: 20
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 1m
      - name: request-duration
        threshold: 500
        interval: 1m
