apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-destinationrule
  namespace: default
spec:
  host: {{ .Release.Name }}-cafeweb.default.svc.cluster.local
  subsets:
    - name: primary
      labels:
        version: primary
    - name: canary
      labels:
        version: canary
