apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}-cafeweb.default.svc.cluster.local
            subset: canary
          weight: 10
        - destination:
            host: {{ .Release.Name }}-cafeweb.default.svc.cluster.local
            subset: primary
          weight: 90
