apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafeapp-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/neehar2601/Cafe_Dynamic_Website_test.git'
    targetRevision: HEAD
    path: Deploy/Cafeapp_progressive_deployment
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

